---
- name: Print OS and Architecture
  ansible.builtin.debug:
    msg:
      - The OS and Architecture is {{ os_arch_version }}
      - The download URL is {{ download_url }}
      - The JDK destination dir is {{ jdk_dest }}
      - The JDK HOME is {{ jdk_home }}

- name: Get JDK
  ansible.builtin.unarchive:
    src: "{{ download_url }}"
    dest: "{{ jdk_dest }}"
    remote_src: true
    creates: "{{ jdk_home }}"

- name: Verify JDK installation
  ansible.builtin.command:
    cmd: "{{ [jdk_home, java_bin_relative_path] | path_join }} --version"
  register: java_version
  changed_when: java_version.rc != 0

- name: Print JDK version
  ansible.builtin.debug:
    msg: "JDK version output: {{ java_version.stdout }}"
