---
- name: Print OS and Architecture
  ansible.builtin.debug:
    msg:
      - The OS and Architecture is {{ os_arch_version }}
      - The download URL is {{ download_url }}
      - The JDK destination dir is {{ jdk_dest }}
      - The JDK HOME is {{ jdk_home }}
      - The JDK file name is {{ jdk_file_name }}
      - The JDK file temp path is {{ jdk_file_temp_path }}
      - The JDK bin path is {{ java_bin_path }}

- name: Install JDK on Windows
  ansible.builtin.include_tasks:
    file: windows.yml
  when: ansible_facts.system == "Win32NT"

- name: Install JDK on Linux or Darwin
  ansible.builtin.include_tasks:
    file: unix.yml
  when: ansible_facts.system == "Linux" or ansible_facts.system == "Darwin"
